UPDATE PARAMEDIC
SET SALARY = SALARY + 
    CASE
        WHEN PARAMEDIC_ID IN (
            SELECT D.PARAMEDIC_ID
            FROM DONATION D
            JOIN DONATION_PLACE DP ON D.PLACE_ID = DP.PLACE_ID
            JOIN PARAMEDIC P ON D.PARAMEDIC_ID = P.PARAMEDIC_ID
            WHERE DP.ADDRESS = '82nd Street'
              AND P.SENIORITY > 2
            GROUP BY D.PARAMEDIC_ID
            HAVING COUNT(D.DONATION_ID) > 5
        ) THEN 600
        WHEN PARAMEDIC_ID IN (
            SELECT D.PARAMEDIC_ID
            FROM DONATION D
            JOIN DONATION_PLACE DP ON D.PLACE_ID = DP.PLACE_ID
            JOIN PARAMEDIC P ON D.PARAMEDIC_ID = P.PARAMEDIC_ID
            WHERE DP.ADDRESS = '82nd Street'
              AND P.SENIORITY > 2
            GROUP BY D.PARAMEDIC_ID
            HAVING COUNT(D.DONATION_ID) > 3
        ) THEN 400
        ELSE 0
    END
WHERE PARAMEDIC_ID IN (
    SELECT D.PARAMEDIC_ID
    FROM DONATION D
    JOIN DONATION_PLACE DP ON D.PLACE_ID = DP.PLACE_ID
    JOIN PARAMEDIC P ON D.PARAMEDIC_ID = P.PARAMEDIC_ID
    WHERE DP.ADDRESS = '82nd Street'
      AND P.SENIORITY > 2
    GROUP BY D.PARAMEDIC_ID
    HAVING COUNT(D.DONATION_ID) > 3
);
